-- Create buttons table
CREATE TABLE buttons (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL
);

CREATE TABLE log (
  id SERIAL PRIMARY KEY,
  button_id INTEGER REFERENCES buttons(id),
  at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);


